### ISSUE TITLE
PhpSpreadsheet is not using securityScan method anymore

### ISSUE THREAD

**Issue by BlackWiCKED** [bseddon/php-pivottables-4-excel-lite#2]
Using the latest dev-master of this library. I get the following error when overriding the Xlsx reader library:

`Attempted to call an undefined method named "securityScan" of class "lyquidity\xbrl_validate\PhpOffice\PhpSpreadsheet\Reader\Xlsx".`

PhpSpreadsheet version 1.15.0 does not have this method anymore. They are using `$this->securityScanner->scan()` now.

**Comment by bseddon** [comment]
Thanks for the report.  I'll take a look a fix it,

**Comment by bseddon** [comment]
Thanks again.  I've updated XlsxReader to use the XmlScanner.
