### ISSUE TITLE
The following repairs were done:_x000d__x000a__x000d__x000a_

### ISSUE THREAD

**Issue by christoph-kloeppner** [bseddon/php-pivottables-4-excel-lite#4]
I always get the following error, after opening the created Excelfile with a pivot table in it:

The following repairs were done:_x000d__x000a__x000d__x000a_"><repairedRecord>Repaired records: PivotTable report from /xl/pivotCache/pivotCacheDefinition619f679649ca5.xml-part (PivotTable Cache).

Any idea? Whats wrong?

**Comment by bseddon** [comment]
Hi

probably some detail of the cache being generated is not correct in  all circumstances.  Are you able to share with me a spreadsheet that causes Excel to show this message when its opened after a pivot table is added?

Thanks

**Comment by bseddon** [comment]
I've just updated the composer.json file so composer should accept any PHP version greater than or equal to 7.0.  While making this change I saw the master branch was 21 commits behind the develop branch.  If you have accessed the master branch then it may explain the message you are seeing Excel emit.  I've updated the master branch so it may be worth updating your copy and trying again.

**Comment by christoph-kloeppner** [comment]
You can close this issue.

**Comment by christoph-kloeppner** [comment]
You can close this issue.
