### ISSUE TITLE
"Real" Filters?

### ISSUE THREAD

**Issue by christoph-kloeppner** [bseddon/php-pivottables-4-excel-lite#5]
Hello again. I am very grateful that you allow us to create a pivot table with your tools.

However, I would need "real" filters for a customer as you see in the screenshot below. Unfortunately, I have not been able to get it to work.

![Screenshot](https://i.ibb.co/RvVDKmw/Bildschirmfoto-2021-11-30-um-15-08-55.png)

**Comment by bseddon** [comment]
So far as I recall (and its been several years) the filter created by the code is equivalent to a 'manual' filter.  I'm not sure that real filter support was ever explicitly implemented.  At the time it was difficult to find formal documentation for the content of the various Xml document required in the xlsx files so I looked at the content Excel creates based on the pivot tables I generated in Excel.   I don't recall whether I tried using real filters.

**Comment by christoph-kloeppner** [comment]
Thank you for your answer. Then it will probably be the case that there are no "real" filters.
